In [172]:
import requests
import pandas as pd
import re
from bs4 import BeautifulSoup


import os
from pandas.io.json import json_normalize
import urllib.request as request
import json

import operator
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [173]:
with request.urlopen("http://www.tanarang.com/english/raagIndex_eng.htm") as res:
    source_data = res.read()

In [174]:
r_data = source_data.decode(encoding='UTF-8')
ragas_list = r_data.split("href")[19:139]

In [175]:
raga_link = []
raga_name = []
for i in ragas_list:
    raga_link.append(i.split("</a>")[0].split(">")[0].split("=")[1].replace('"',""))
    raga_name.append(i.split("</a>")[0].split(">")[1])

In [176]:
jati = []; thaat =[]; vadi_samvadi=[]; time=[]; mukhya_ang=[]; aaroh_avroh=[]; raag_url=[];ragaName=[]
for link,raga_n in zip(raga_link,raga_name):
    RAGA_URL = "http://www.tanarang.com/english/" + link
    raag_url.append(RAGA_URL)
    ragaName.append(raga_n)
    print(RAGA_URL)
    with request.urlopen(RAGA_URL) as res:
        #print(res)
        source_data = res.read()
   
    r_data = source_data.decode(encoding='UTF-8')
    #print(r_data.split("Jati</a></td>\r\n<td>"))
    if (r_data.find("Jati</a>") ==-1):
        jati.append("-")
    else:
        jati.append(r_data.split("Jati</a></td>\r\n<td")[1].split("</td></tr>")[0])
    if (r_data.find("Thaat</a>") ==-1):
        thaat.append("-")
    else:
        thaat.append(r_data.split("Thaat</a></td>\r\n<td")[1].split("</td></tr>")[0])
    if (r_data.find("Vadi/Samvadi</a>") ==-1):
        vadi_samvadi.append("-")
    else:
        vadi_samvadi.append(r_data.split("Vadi/Samvadi</a></td>\r\n<td")[1].split("</td></tr>")[0])
    if (r_data.find("Time</a>") ==-1):
        time.append("-")
    else:
        time.append(r_data.split("Time</a></td>\r\n<td")[1].split("</td></tr>")[0])
    if (r_data.find("Mukhya-Ang</a>") ==-1):
        mukhya_ang.append("-")
    else:
        mukhya_ang.append(r_data.split("Mukhya-Ang</a></td>\r\n<td")[1].split("</td></tr>")[0])
    if (r_data.find("Aaroh-Avroh</a>") ==-1):
        aaroh_avroh.append("-")
    else:
        aaroh_avroh.append(r_data.split("Aaroh-Avroh</a></td>\r\n<td")[1].split("</td></tr>")[0])

http://www.tanarang.com/english/abhogi_eng.htm
http://www.tanarang.com/english/adana_eng.htm
http://www.tanarang.com/english/aheer-bhairav_eng.htm
http://www.tanarang.com/english/alhaiya_eng.htm
http://www.tanarang.com/english/bageshree_eng.htm
http://www.tanarang.com/english/bahaar_eng.htm
http://www.tanarang.com/english/bairagi_eng.htm
http://www.tanarang.com/english/bairagi-todi_eng.htm
http://www.tanarang.com/english/basant_eng.htm
http://www.tanarang.com/english/basant-mukhari_eng.htm
http://www.tanarang.com/english/bhairav_eng.htm
http://www.tanarang.com/english/bhairavi_eng.htm
http://www.tanarang.com/english/bhatiyar_eng.htm
http://www.tanarang.com/english/bheem_eng.htm
http://www.tanarang.com/english/bheempalasi_eng.htm
http://www.tanarang.com/english/bhoopali_eng.htm
http://www.tanarang.com/english/bhupal-todi_eng.htm
http://www.tanarang.com/english/bihag_eng.htm
http://www.tanarang.com/english/bihagda_eng.htm
http://www.tanarang.com/english/bilaskhani-todi_eng.htm
http://www.tanarang.com/english/chandra-kauns_eng.htm
http://www.tanarang.com/english/charukeshi_eng.htm
http://www.tanarang.com/english/chhayanut_eng.htm
http://www.tanarang.com/english/darbari_kanada_eng.htm
http://www.tanarang.com/english/des_eng.htm
http://www.tanarang.com/english/deshkar_eng.htm
http://www.tanarang.com/english/desi_eng.htm
http://www.tanarang.com/english/dev-gandhar_eng.htm
http://www.tanarang.com/english/devgiri-bilawal_eng.htm
http://www.tanarang.com/english/devsakh_eng.htm
http://www.tanarang.com/english/devshree_eng.htm
http://www.tanarang.com/english/dhanashree_eng.htm
http://www.tanarang.com/english/dhani_eng.htm
http://www.tanarang.com/english/durga_eng.htm
http://www.tanarang.com/english/gaud-malhar_eng.htm
http://www.tanarang.com/english/gaud-sarang_eng.htm
http://www.tanarang.com/english/gauri_eng.htm
http://www.tanarang.com/english/gopika-basant_eng.htm
http://www.tanarang.com/english/gorakh-kalyan_eng.htm
http://www.tanarang.com/english/gunkali_eng.htm
http://www.tanarang.com/english/gurjari-todi_eng.htm
http://www.tanarang.com/english/hameer_eng.htm
http://www.tanarang.com/english/hans-dhwani_eng.htm
http://www.tanarang.com/english/hans-kinkini_eng.htm
http://www.tanarang.com/english/hari-kauns_eng.htm
http://www.tanarang.com/english/hemant_eng.htm
http://www.tanarang.com/english/hemshri_eng.htm
http://www.tanarang.com/english/hindol_eng.htm
http://www.tanarang.com/english/jaijaivanti_eng.htm
http://www.tanarang.com/english/jaldhar-kedar_eng.htm
http://www.tanarang.com/english/jaunpuri_eng.htm
http://www.tanarang.com/english/jayat_eng.htm
http://www.tanarang.com/english/jhinjhoti_eng.htm
http://www.tanarang.com/english/jog_eng.htm
http://www.tanarang.com/english/jogeshwari_eng.htm
http://www.tanarang.com/english/pancham_jogeshwari_eng.htm
http://www.tanarang.com/english/jogiya_eng.htm
http://www.tanarang.com/english/jogkauns_eng.htm
http://www.tanarang.com/english/kafi_eng.htm
http://www.tanarang.com/english/kalawati_eng.htm
http://www.tanarang.com/english/kamod_eng.htm
http://www.tanarang.com/english/kaushik-dhwani_eng.htm
http://www.tanarang.com/english/kausi-kanada_eng.htm
http://www.tanarang.com/english/kedar_eng.htm
http://www.tanarang.com/english/keerwani_eng.htm
http://www.tanarang.com/english/khamaj_eng.htm
http://www.tanarang.com/english/khambavati_eng.htm
http://www.tanarang.com/english/komal-rishabh-asawari_eng.htm
http://www.tanarang.com/english/lalit_eng.htm
http://www.tanarang.com/english/lanka-dahan-sarang_eng.htm
http://www.tanarang.com/english/madhukauns_eng.htm
http://www.tanarang.com/english/madhumad-sarang_eng.htm
http://www.tanarang.com/english/madhuvanti_eng.htm
http://www.tanarang.com/english/malgunji_eng.htm
http://www.tanarang.com/english/malhar_eng.htm
http://www.tanarang.com/english/malkauns_eng.htm
http://www.tanarang.com/english/mand_eng.htm
http://www.tanarang.com/english/maru-bihag_eng.htm
http://www.tanarang.com/english/marwa_eng.htm
http://www.tanarang.com/english/megh_eng.htm
http://www.tanarang.com/english/mohan-kauns_eng.htm
http://www.tanarang.com/english/multani_eng.htm
http://www.tanarang.com/english/nand_eng.htm
http://www.tanarang.com/english/narayani_eng.htm
http://www.tanarang.com/english/nayaki-kanada_eng.htm
http://www.tanarang.com/english/nut-bhairav_eng.htm
http://www.tanarang.com/english/parameshwari_eng.htm
http://www.tanarang.com/english/patdeep_eng.htm
http://www.tanarang.com/english/pilu_eng.htm
http://www.tanarang.com/english/puriya_eng.htm
http://www.tanarang.com/english/puriya-dhanashri_eng.htm
http://www.tanarang.com/english/puriya-kalyan_eng.htm
http://www.tanarang.com/english/purvi_eng.htm
http://www.tanarang.com/english/rageshree_eng.htm
http://www.tanarang.com/english/ramdasi-malhar_eng.htm
http://www.tanarang.com/english/ramkali_eng.htm
http://www.tanarang.com/english/salag-varali_eng.htm
http://www.tanarang.com/english/vrindavani-sarang_eng.htm
http://www.tanarang.com/english/saraswati_eng.htm
http://www.tanarang.com/english/saraswati-kedar_eng.htm
http://www.tanarang.com/english/shahana-kanada_eng.htm
http://www.tanarang.com/english/shankara_eng.htm
http://www.tanarang.com/english/shivranjani_eng.htm
http://www.tanarang.com/english/shobhawari_eng.htm
http://www.tanarang.com/english/shriraag_eng.htm
http://www.tanarang.com/english/shuddha-kalyan_eng.htm
http://www.tanarang.com/english/shuddha-sarang_eng.htm
http://www.tanarang.com/english/shyam-kalyan_eng.htm
http://www.tanarang.com/english/sindhura_eng.htm
http://www.tanarang.com/english/sohani_eng.htm
http://www.tanarang.com/english/suha-sughrai_eng.htm
http://www.tanarang.com/english/sundarkali_eng.htm
http://www.tanarang.com/english/sundar-kauns_eng.htm
http://www.tanarang.com/english/surdasi-malhar_eng.htm
http://www.tanarang.com/english/tilak-kamod_eng.htm
http://www.tanarang.com/english/tilang_eng.htm
http://www.tanarang.com/english/tilang-bahar_eng.htm
http://www.tanarang.com/english/todi_eng.htm
http://www.tanarang.com/english/vachaspati_eng.htm
http://www.tanarang.com/english/vibhas_eng.htm

In [177]:
av=[]
for i in aaroh_avroh:
    if (i.find("<strong>") == -1):
        av.append(i)
    else:
        if (i.find("</strong>") == -1):
            av.append(i.split("<strong>")[1].replace("'",""))
        else:
            av.append(i.split("<strong>")[1].split("</strong>")[0].replace("'",""))

In [178]:
ma=[]
for i in mukhya_ang:
    if (i.find("<strong>") == -1):
        ma.append(i)
    else:
        if (i.find("</strong>") == -1):
            ma.append(i.split("<strong>")[1].replace("'","").replace("’",""))
        else:
            ma.append(i.split("<strong>")[1].split("</strong>")[0].replace("'","").replace("’",""))

In [179]:
jati_ = []
for i in jati:
   jati_.append(i.split(">")[1].replace("Vakra", "").replace(" ",""))

In [180]:
time_ =[]
for i in time:
    time_.append(i.split(">")[1])

In [181]:
#1st Prahar of the Day , Second Prahar of the Night: Early Morning
#2nd Prahar of the day: Late morning
#3rd Prahar of the day: Afternoon
#4th Prahar of the day: Dusk

#1st Prahar of the night: Evening
#2nd Prahar of the Night : Night
#4th Prahar of the Night: Dawn
#3rd Prahar of the Night: Midnight
time__ = []

for i in time_:
    if (i.lower().find("1st prahar of the day") != -1):
        time__.append("Early Morning")
    
        
    elif (i.lower().find("2nd prahar of the day") != -1):
        time__.append("Late morning")
   
        
    elif (i.lower().find("3rd prahar of the day") != -1):
        time__.append("Afternoon")
   
        
    elif (i.lower().find("4th prahar of the day") != -1):
        time__.append("Dusk")
    

    elif (i.lower().find("1st prahar of the night") != -1):
        time__.append("Evening")
   
        
    elif (i.lower().find("2nd prahar of the night") != -1):
        time__.append("Night")
   
        
    elif (i.lower().find("3rd prahar of the night") != -1):
        time__.append("Dawn")
  
        
    elif (i.lower().find("4th prahar of the night") != -1):
        time__.append("Midnight")
        
        
    else:
        time__.append(i)

In [182]:
thaat_ =[]
for i in thaat:
    if (i.find(" >") == -1):
        thaat_.append(i)
    else:
        if (i.find("(") == -1):
            thaat_.append(i.split(" >")[1])
        else:
            thaat_.append(i.split(" >")[1].split("(")[0])

In [183]:
vadi_ = []; samvadi_ = []
for i in vadi_samvadi:
    if (i.find(" >") == -1):
        vadi_.append(i)
        samvadi_.append(i)
    else:
        vadi_.append(i.split(" >")[1].split("/")[0])
        samvadi_.append(i.split(" >")[1].split("/")[1])

In [184]:
df= pd.DataFrame(list(zip(thaat_,vadi_,samvadi_,jati_,time__,ma,av,ragaName,raag_url)), columns =['Thaat','Vadi','Samvadi','Jati','Time of day','Mukhya-Ang','Aaroh-Avroh', 'Raag', 'link'])

In [185]:
df

,Thaat,Vadi,Samvadi,Jati,Time of day,Mukhya-Ang,Aaroh-Avroh,Raag,link
0,Kafi,Madhyam,Shadj,Audhav-Audhav,Night,"><b>S R ,D S ; R g m ; g m R S;</b>","S R g m D S - S D m g R g m R S ; R ,D ,D S ;",Abhogi Kanada,http://www.tanarang.com/english/abhogi_eng.htm
1,Asawari,Shadj,Pancham,Shadhav-Sampurna,Night,m P d n S; S d n S ; S d n P ; m P ; g m R S;,S R m P d n S - S d n P ; m P g m R S;,Adana,http://www.tanarang.com/english/adana_eng.htm
2,Bhairav,Madhyam,Shadj,Sampurna-Sampurna,Early Morning,G m P ; D n D ; P D P ; S n D ; n D P m G m ; ...,S r G m P D n S - S n D P m G r S,Aheer Bhairav,http://www.tanarang.com/english/aheer-bhairav_...
3,Bilawal,Dhaivat,Gandhar,Shadhav-Sampurna,Early Morning,G R G P ; D n D P ; m G R ; G P D N S ;,S R G P D N S - S N D P D n D P m G R S;,Alhaiya Bilawal,http://www.tanarang.com/english/alhaiya_eng.htm
4,Kafi,Madhyam,Shadj,Shadhav-Sampurna,Night,",n S m ; S g m ; g R S ; ,n ,D ; m D n D ; m g...","S R g m D n S - S n D m P D m g R S; ,n S;",Bageshree,http://www.tanarang.com/english/bageshree_eng.htm
...,...,...,...,...,...,...,...,...,...
115,Khamaj,Gandhar,Nishad,Audhav-Audhav,Night,G m P n P m G ; n P G m G ;,S G m P N S - S n P m G S;,Tilang,http://www.tanarang.com/english/tilang_eng.htm
116,Khamaj,Gandhar,Nishad (when Tilang is dominant) or Madhyam,ShadhavSampurna,Night,m P m g ; m ; n P m ; P N S ; g m P m g m R S,S R S m ; G m P n P ; m D N S - S n P m g m R S,Tilang Bahar,http://www.tanarang.com/english/tilang-bahar_e...
117,Todi,Dhaivat,Gandhar,Sampurna-Sampurna,Late morning,",d ; ,N S r g ; M r g ; r S;",S r g M P d N S - S N d P M g r S;,Todi,http://www.tanarang.com/english/todi_eng.htm
118,Carnatic Music System,Shadj,Pancham,Audhav-Sampurna,Dusk,",n S G M ; P D P ; M G R S ; R ,n S ; M G R S ;","S G M P n S - S n D P M G R S; ,n S;",Vachaspati,http://www.tanarang.com/english/vachaspati_eng...
119,Bhairav,Dhaivat,Rishabh,Audhav-Audhav,Early Morning,P d d P ; G P G r S ;,S r G P d S - S d P G r S ;,Vibhas,http://www.tanarang.com/english/vibhas_eng.htm

In [186]:
df.to_csv("hindustani_ragas_data_.csv")

In [187]:
data_update = pd.read_csv("hindustani_ragas_data.csv") #preprocessed dataset

In [188]:
S=[];r=[];R=[];g=[];G=[];m=[];M=[];P=[];d=[];D=[];n=[];N=[]
for i,j in zip(data_update['Mukhya-Ang'],data_update['Aaroh-Avroh']):
    S.append(i.count("S") + j.count("S"))
    r.append(i.count("r") + j.count("r"))
    R.append(i.count("R") + j.count("R"))
    g.append(i.count("g") + j.count("g"))
    G.append(i.count("G") + j.count("G"))
    m.append(i.count("m") + j.count("m"))
    M.append(i.count("M") + j.count("M"))
    P.append(i.count("P") + j.count("P"))
    d.append(i.count("d") + j.count("d"))
    D.append(i.count("D") + j.count("D"))
    n.append(i.count("n") + j.count("n"))
    N.append(i.count("N") + i.count("N"))

In [189]:
k ="S=[];r=[];R=[];g=[];G=[];m=[];M=[];P=[];d=[];D=[];n=[];N=[]"
j = k.replace("=[];",",").split("=")[0]
j

'S,r,R,g,G,m,M,P,d,D,n,N'

In [190]:
j.replace(",",',"' ).replace(",",'",').replace("S",'"S').replace("N",'N"')

'"S","r","R","g","G","m","M","P","d","D","n","N"'

In [191]:
df2 = pd.DataFrame(list(zip(S,r,R,g,G,m,M,P,d,D,n,N)), columns =["S","r","R","g","G","m","M","P","d","D","n","N"])
df2

     S  r  R  g  G  m  M  P  d  D  n  N
0    8  0  7  5  0  5  0  0  0  5  0  0
1    9  0  3  2  0  6  0  6  5  0  5  0
2    7  6  0  0  5  7  0  7  0  8  7  0
3    5  0  4  0  6  2  0  6  0  7  2  2
4    9  0  4  5  0  7  0  1  0  6  6  0
..  .. .. .. .. .. .. .. .. .. .. .. ..
117  6  5  0  4  0  0  3  2  3  0  0  2
118  9  0  4  0  5  0  5  4  0  2  5  0
119  5  3  0  0  4  0  0  5  4  0  0  0
120  6  2  0  0  2  0  4  4  2  3  4  0
121  5  0  2  0  1  5  0  4  1  2  2  0

[122 rows x 12 columns]

In [192]:
notes =df2.astype(bool).astype(int)
notes

     S  r  R  g  G  m  M  P  d  D  n  N
0    1  0  1  1  0  1  0  0  0  1  0  0
1    1  0  1  1  0  1  0  1  1  0  1  0
2    1  1  0  0  1  1  0  1  0  1  1  0
3    1  0  1  0  1  1  0  1  0  1  1  1
4    1  0  1  1  0  1  0  1  0  1  1  0
..  .. .. .. .. .. .. .. .. .. .. .. ..
117  1  1  0  1  0  0  1  1  1  0  0  1
118  1  0  1  0  1  0  1  1  0  1  1  0
119  1  1  0  0  1  0  0  1  1  0  0  0
120  1  1  0  0  1  0  1  1  1  1  1  0
121  1  0  1  0  1  1  0  1  1  1  1  0

[122 rows x 12 columns]

### pre - processing

In [193]:
data_update["Thaat"] = data_update["Thaat"].replace(to_replace =["-", "Not Defined"], 
                            value ="other")
data_update["Thaat"] = data_update["Thaat"].replace(to_replace =["Khamaj "], 
                            value ="Khamaj")

In [194]:
data_update["Thaat"].unique()

array(['Kafi', 'Asawari', 'Bhairav', 'Bilawal', 'Todi', 'Poorvi',
       'Bhairavi', 'Marwa', 'Kalyan', 'other', 'Khamaj',
       'Carnatic Music System'], dtype=object)

In [195]:
data_update["Vadi"] = data_update["Vadi"].replace(to_replace =["-"], 
                            value ="Other")
data_update["Vadi"] = data_update["Vadi"].replace(to_replace =["Tar Shadj"], 
                            value ="Shadj")

In [196]:
data_update["Vadi"].unique()

array(['Madhyam', 'Shadj', 'Dhaivat', 'Pancham', 'Gandhar', 'Rishabh',
       'Nishad', 'Other'], dtype=object)

In [197]:
data_update["Samvadi"] = data_update["Samvadi"].replace(to_replace =["-"], 
                            value ="Other")
data_update["Samvadi"] = data_update["Samvadi"].replace(to_replace =["Shuddha Nishad"], 
                            value ="Nishad")

In [198]:
data_update["Samvadi"].unique()

array(['Shadj', 'Pancham', 'Gandhar', 'Rishabh', 'Dhaivat', 'Nishad',
       'Madhyam', 'Other'], dtype=object)

In [199]:
data_update["Jati"] = data_update["Jati"].replace(to_replace =["ShadhavSampurna"], 
                            value ="Shadhav-Sampurna")
data_update["Jati"] = data_update["Jati"].replace(to_replace =["Audha-Audhav"], 
                            value ="Audhav-Audhav")

In [200]:
data_update["Jati"].unique()

array(['Audhav-Audhav', 'Shadhav-Sampurna', 'Sampurna-Sampurna',
       'Audhav-Shadhav', 'Audhav-Sampurna', 'Shadhav-Shadhav',
       'Sampurna-Shadhav'], dtype=object)

In [201]:
data_update["Time of day"] = data_update["Time of day"].replace(to_replace =["Second Prahar of the Night or Anytime in Spring Season."], 
                            value ="Night")
data_update["Time of day"] = data_update["Time of day"].replace(to_replace =["Din ka Tritiya Prahar"], 
                            value ="Afternoon")
data_update["Time of day"] = data_update["Time of day"].replace(to_replace =["Sandhi-Prakash Raag"], 
                            value ="Dusk")#could be dawn or dusk, in this case it is dusk
data_update["Time of day"] = data_update["Time of day"].replace(to_replace =["(12 AM - 3 AM): 3 rd Prahar of the Night: Ratri ka Teesra Prahar"], 
                            value ="Midnight")
data_update["Time of day"] = data_update["Time of day"].replace(to_replace =["1sh Prahar of the day : Din ka Pratham Prahar", "(6 AM - 9 AM): Din ka Pratham Prahar "], 
                            value ="Early Morning")
data_update["Time of day"] = data_update["Time of day"].replace(to_replace =["Rainy Season - All times", "Anytime in Rainy season.",
       "Anytime in Rainy Season"], 
                            value ="Anytime")

In [202]:
data_update["Time of day"].unique()

array(['Night', 'Early Morning', 'Late morning', 'Midnight', 'Afternoon',
       'Evening', 'Dawn', 'Dusk', 'Anytime'], dtype=object)

In [203]:
#outer join
ragas_dataset = pd.concat([data_update, notes], axis=1, join='inner')
ragas_dataset.head()

,Unnamed: 0,Thaat,Vadi,Samvadi,Jati,Time of day,Mukhya-Ang,Aaroh-Avroh,Raag,link,...,R,g,G,m,M,P,d,D,n,N
0,0,Kafi,Madhyam,Shadj,Audhav-Audhav,Night,"S R ,D S ; R g m ; g m R S;","S R g m D S - S D m g R g m R S ; R ,D ,D S ;",Abhogi Kanada,http://www.tanarang.com/english/abhogi_eng.htm,...,1,1,0,1,0,0,0,1,0,0
1,1,Asawari,Shadj,Pancham,Shadhav-Sampurna,Night,m P d n S; S d n S ; S d n P ; m P ; g m R S;,S R m P d n S - S d n P ; m P g m R S;,Adana,http://www.tanarang.com/english/adana_eng.htm,...,1,1,0,1,0,1,1,0,1,0
2,2,Bhairav,Madhyam,Shadj,Sampurna-Sampurna,Early Morning,G m P ; D n D ; P D P ; S n D ; n D P m G m ; ...,S r G m P D n S - S n D P m G r S,Aheer Bhairav,http://www.tanarang.com/english/aheer-bhairav_...,...,0,0,1,1,0,1,0,1,1,0
3,3,Bilawal,Dhaivat,Gandhar,Shadhav-Sampurna,Early Morning,G R G P ; D n D P ; m G R ; G P D N S ;,S R G P D N S - S N D P D n D P m G R S;,Alhaiya Bilawal,http://www.tanarang.com/english/alhaiya_eng.htm,...,1,0,1,1,0,1,0,1,1,1
4,4,Kafi,Madhyam,Shadj,Shadhav-Sampurna,Night,"n S m ; S g m ; g R S ; ,n ,D ; m D n D ; m g ...","S R g m D n S - S n D m P D m g R S; ,n S;",Bageshree,http://www.tanarang.com/english/bageshree_eng.htm,...,1,1,0,1,0,1,0,1,1,0

In [204]:
ragas_dataset.to_csv("ragas_dataset_viz2educate.csv")